### ISSUE TITLE
409 Conflict with syntax error bug?

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/ermrest#114] opened 2016-10-21 23:04 UTC
When making a `PUT` request to `dev.gpcrconsortium.org/ermrest/catalog/1/entity/experiments:experiment_type?cid=recordedit` with this request payload:

```
[
    {id: 8, name: "AB ExpType 1"}
]
```

I get the following error:
```
409 Conflict
The request conflicts with the state of the server. syntax error at or near "FROM"
LINE 2: UPDATE "experiments"."experiment_type" t SET  FROM (
```

Here is the schema document for catalog 1, schema `experiments`, table `experiment_type` on `dev.gpcrconsortium.org`:
```
{
comment: null,
kind: "table",
keys: [
{
comment: null,
annotations: { },
unique_columns: [
"name"
]
},
{
comment: null,
annotations: { },
unique_columns: [
"id"
]
}
],
foreign_keys: [ ],
table_name: "experiment_type",
schema_name: "experiments",
column_definitions: [
{
comment: null,
name: "id",
default: null,
nullok: false,
type: {
typename: "serial4"
},
annotations: {
tag:misd.isi.edu,2015:hidden: null
}
},
{
comment: null,
name: "name",
default: null,
nullok: false,
type: {
typename: "text"
},
annotations: { }
}
],
annotations: { }
}
```

**Comment by karlcz** [comment] 2016-10-25 00:16
This is fixed in ermrest/master and should no longer return 409 w/ the SQL syntax error.  Instead, it should do one of the following:

- 200 OK  if the input data already exists or can be safely inserted
- 409 Conflict with a better error message if the input data does not exist but an insert will conflict with existing row data due to having more than one uniqueness constraint on the same table.

**Comment by karlcz** [comment] 2016-10-25 00:17
@howdyjessie if you can reproduce the original error scenario, could you verify that this works as described in my previous message (once latest code is updated on dev server)?

**Comment by karlcz** [comment] 2016-10-25 18:21
Thanks, I'll have to clean that up...

The underlying special case is that all columns in this table are key
material, so there are no columns left to treat as an update. (The PUT
/entity/ API only updated non-key columns.)

It should just interpret this case as "idempotent insert" since there
are no columns to update.  Based on your error message, it looks like
we must have forgotten to handle this case and instead blindly built
an update statement without any target columns listed...

**Comment by howdyjessie** [comment] 2016-10-25 18:25
@karlcz It looks the fix works. I tested this again and now receive 200 OKs.

**Closed** 2016-10-25 18:27 UTC

**Comment by hongsudt** [comment] 2016-10-25 18:29
I have discussed this case with Karl. This is because the current record
edit try to modify the unique key columns, which will fail unless you pass
the old and new unique key values to ermrest.

Josh has implemented this support in the new recordedit. So let's not fix
this in the old app and get the new one pushed asap.
