### ISSUE TITLE
Difficulties using high-precision columns for attributegroup row correlation

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrest#141] opened 2017-03-25 02:10 UTC
It appears that this [issue](https://github.com/informatics-isi-edu/chaise/issues/1029) after investigating both `chaise` and `ermrestJS` is being caused by ermrest.

I was able to verify that floats are being handled appropriately. I tested this on an entity with both a float and timestamptz column. I first created an entity with only the timestamp value set. After creation I tried updating it by just resubmitting the data, and I saw a 409 conflict. 

I then created another entity for the same table where just the float value was set. I tried updating it after by just resubmitting the data and saw a success.

I then went and verified the network log in my browser console to see what data was received on the initial read compared to the data on the PUT request. There is no difference in these 2 sets of data.

Upon further inspection of the error message, I notice this:
`datetime.datetime(2017, 3, 21, 11, 33, 46, 873307, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-420, name=None))`

Could it be related to a timestamp value not being evaluated properly? Or maybe it has to do with daylights savings that happened just under 2 weeks ago (somewhat consistent with when we started seeing these errors)?

**Comment by karlcz** [comment] 2017-03-25 17:56
Be aware that the funny looking values in the 409 Conflict error are a red herring. The actual request data goes directly from the HTTP connection into PostgreSQL where the JSON is deserialized natively in the DB.  The row conflicts are detected by a SQL query but the conflicting row data is retrieved and converted into Python data before it gets into the error message.  We can improve the appearance of this error message but it has no impact on the ability to successfully process these requests...

Also, I need more concrete details of a failing test case if there really is a timestamp conflict:

1. An exact record on a test server we are discussing, e.g. entity API URL to record
2. Exact request/response seen to load existing record content to Chaise
    - ermrest URL
    - JSON response from ERMrest
3. Exact request sent to ERMrest
    - ermrest URL
    - JSON request content
4. Complete error response from ERMrest

If it's the real problem, we should be able to recreate it using only two columns for correlation: the primary row key and the one timestamp column. So far, I am unable to reproduce any timestamp conflict.  On both synapse-dev and gpcr-dev systems, I found records that fail using Chaise and then tried to simulate these failures directly with HTTP requests formed from `curl` where I could dig in deeper.  My method:

1. Identify one record and save the original get-entity response JSON to a file test.json which looks like an array of one object.
2. Edit the test.json to add one extra column to the object to act as the "new" column value for an update
    - for gpcr assets.sec table I added `NEWdescription` and copied the existing text value
    - for synapse Zebrafish.Behavior table I added `NEWFScope` and copied the existing text value
3. Simulate the Chaise update request in spirit to replicate the 409 Conflict, e.g. correlate on all columns and update the "new" one
    - for gpcr I used /ermrest/catalog/1/attributegroup/assets:sec/*;NEWdescription
    - for synapse I used /ermrest/catalog/1/attributegroup/Zebrafish:Behavior/*;NEWFScope
4. Do pairwise tests with primary key and each candidate column to see which values are not matching
    - for gpcr I used /ermrest/catalog/1/attributegroup/assets:sec/id,candidate;NEWdescription
    - for synapse I used /ermrest/catalog/1/attributegroup/Zebrafish:Behavior/ID,candidate;NEWFScope

I got the failure as expected in step (3). But when narrowing down the problem in step (4), I found that on synapse the failing columns were the two "metadata" columns of type JSON, while on gpcr the failing columns are the measurements with type float8.  The `timestamptz` columns in my test actually had no problem for any of the test records I tried.

So, I still think this is a precision and round-trip fidelity hazard with several different causes:

1. `float8` and `int8` precision is quite likely a problem due to many levels of conversion where information loss could occur:
    - postgres serializing the native number into a decimal number in the JSON serialization
    - JSON has only limited numeric representations available in the standard
    - the browser deserializing the response JSON back into a native JS number
    - javascript has limited numeric precision in its standard and typical implementations
    - the browser serializing the number back into request JSON
    - postgres deserializing the request JSON back into native column type
2. Timestamp precision may eventually be an issue if postgres is storing more fractional second information than we are serializing into the timestamp strings, e.g. milliseconds, microseconds, or nanoseconds.
3. Chaise and/or ermrestjs don't seem to handle JSON column types but instead turn them into a string literal, e.g. a column containing an object like `{"a": true}` gets turned into a string like `"{\"a\": true}"` which is a very different JSON meaning.
4. Also, a SQL NULL and a JSON value of `null` are distinct states for a column of type `json` or `jsonb`. But both column states will appear as a JSON `null` in the ERMrest row object using `application/json` response type. They are distinguishable in `text/csv` responses where the JSON representation is present as a string or completely absent for a SQL NULL.

I think we'd have to attack each of these different hazards with slightly different methods:
- High precision timestamps may need to be serialized into a higher precision string representation than they are now in ERMrest
- High precision numbers (both float and int8) may need to be serialized as string literals rather than numbers for JSON responses from ERMrest. (I think other web APIs do this for the same reason, e.g. Twitter uses strings for their big integers.)
- Normalize the two forms of null for JSON columns in ERMrest, so they can no longer be distinguished or ambiguous
- Add proper `json` and `jsonb` column handling in ermrestjs and Chaise for display and editing

Any changes to the representation of timestamps and numbers may be API compatibility changes we'll need to coordinate between ERMrest, ermrestjs, and Chaise. The current native number approach is intuitive for naive clients but exposes all these gaps in the standards. Using string literals means that clients need to be cognizant of the issue and juggle exact number strings versus lossy, native representations depending on application context.  A short-term workaround for the float problems might be to use `float4` instead of `float8` in catalogs where that extra precision or dynamic range isn't really important, as I think the native precision is good enough for these.

All the trouble here is trying to test bit-for-bit equality that a row in the database matches what we think we were editing. Even if we drop this data-precondition approach to making updates via attributegroup in Chaise, we'd be back to potential 412 false positives for ETags and struggling to solve the same data equality problem but on the client side. The simplest workaround here is to overwrite blindly and follow a last-writer-wins strategy from Chaise, using simpler ERMrest requests that do not try to compare data exactly...

@hongsudt @robes

**Comment by karlcz** [comment] 2017-03-29 01:12
I checked and postgres timestamp precision is currently 1 microsecond which we are fully capturing as 6 decimal digits of fractional seconds in our serlaized output, e.g. 

    2017-03-14T15:40:54.390626-07:00

so as long as we return the full string we should not have any losses for timestamp.  But, float8 remains a problem as discussed above.

**Comment by karlcz** [comment] 2017-05-11 21:27
I am leaning towards closing this as wontfix for the float8 case.  Users should just avoid trying to use such columns in a correlation key.  A more general solution would require non backward-compatible changes to ERMrest such as to introduce stable row keys to use in row update requests independent of the application-specific model's columns.

**Closed** 2017-05-30 20:52 UTC
Labels: wontfix
