### ISSUE TITLE
APIs to retrieve data summary such as histogram

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrest#147] opened 2017-04-19 18:17 UTC
- number, date/datetime : histogram
- boolean: histogram of true/false/null
- text (vocab) : word frequency 
- free text : no aggregate
- json: no aggregate

**Comment by karlcz** [comment] 2017-04-19 18:23
This seems like a duplicate of #134

**Comment by karlcz** [comment] 2017-04-19 18:41
And there's already an ermrest API that can give you text counts assuming you mean number of rows that have an exact text value:

    GET /ermrest/catalog/N/attributegroup/Schema:Table/Column;Count:=cnt(*)

this will return a table of results with each row having a "Column" field with a specific value and a "Count" field for the number of rows in Table that had this value.  The reason we need a different histogram API is that the attributegroup API only groups by actual column values.  It does not have any value truncation/binning mechanism to group by those coarser granularity approximations instead.

If you're hoping for word frequency counts within a text value, e.g. breaking paragraphs and sentences into words and counting them, that seems far out of scope for what ermrest offers currently.

**Comment by karlcz** [comment] 2017-04-19 18:49
closing duplicate

**Closed by karlcz** 2017-04-19 18:49 UTC
